version: "2.1"

services:
  mqtt:
    image: eclipse-mosquitto
    ports:
      - "1883:1883"
    volumes:
      - "./config/mosquitto.conf:/mosquitto/config/mosquitto.conf"
  database:
    image: mongo
    ports:
      - "27017:27017"
