name: Quality

on:
  pull_request:
    branches: [master]

jobs:
  quality:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout project
        uses: actions/checkout@v2

      - name: Set up Go 1.X
        uses: actions/setup-go@v2
        with:
          go-version: ^1.13
        id: go

      - name: Cache Go modules
        uses: actions/cache@preview
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-build-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install dependencies
        run: go get -v -t -d ./...

      - name: Build
        run: go build -v .

      - name: Unit tests
        run: go test -v ./...
