name: Quality

on:
  pull_request:
    branches: [master]

jobs:
  quality:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout project
        uses: actions/checkout@v2

      - name: Set up Go 1.X
        uses: actions/setup-go@v2
        with:
          go-version: ^1.13
        id: go

      - name: Cache Go modules
        uses: actions/cache@preview
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-build-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install dependencies
        run: go get -v -t -d ./...

      - name: Build
        run: go build -v .

      - name: Coverage
        uses: paambaati/codeclimate-action@v2.2.4
        env:
          CC_TEST_REPORTER_ID: 2ab99af35ea29d5d98540488d5ca0faca5b45ef0e6b0f91c8745a267a2b1bad3
        with:
          coverageCommand: go test -v ./... -coverprofile c.out
